Setting list of files
DoumanAsh/clipboard-win pull request #24
Opened 2023-01-04 15:49 UTC by mchels

I want to add setting files on the clipboard according to these links

https://stackoverflow.com/questions/25708895/how-to-copy-files-by-win32-api-functions-and-paste-by-ctrlv-in-my-desktop
https://forums.codeguru.com/showthread.php?565003-SetClipboardData()-to-Copy-File
https://forum.lazarus.freepascal.org/index.php?topic=51601.0
https://stackoverflow.com/questions/27278659/copy-a-file-to-clipboard-in-delphi
https://devblogs.microsoft.com/oldnewthing/20130520-00/?p=4313
https://learn.microsoft.com/en-us/windows/win32/shell/clipboard#cf_hdrop
https://github.com/luapower/winapi/blob/master/winapi/clipboard.lua#L187
https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/ns-shlobj_core-dropfiles
https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/Shell/struct.DROPFILES.html
https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Foundation/struct.BOOL.html
https://github.com/gabdube/native-windows-gui/blob/10f2ac484b25368abc286f4d90562c3a27f22595/native-windows-gui/src/events.rs
https://github.com/alex8088/clipboard-files/blob/master/src/clip_win.cc

I get an error in the test that I added, though:

```
C:\Users\UMRH\repos\clipboard-win>cargo test should_work_with_filelist -- --exact --nocapture
   Compiling clipboard-win v4.4.2 (C:\Users\UMRH\repos\clipboard-win)
    Finished test [unoptimized + debuginfo] target(s) in 2.60s
     Running unittests src\lib.rs (target\debug\deps\clipboard_win-accf31e6a3daf1f9.exe)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests\formats.rs (target\debug\deps\formats-882388a362906242.exe)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.00s

     Running tests\test_clip.rs (target\debug\deps\test_clip-66edde24978329a6.exe)

running 1 test
0x9b75fef48
0x12cb0e047a0
0x12cb0dedcb0
20
0x12cb0dedcb0
48
error: test failed, to rerun pass '--test test_clip'

Caused by:
  process didn't exit successfully: `C:\Users\UMRH\repos\clipboard-win\target\debug\deps\test_clip-66edde24978329a6.exe should_work_with_filelist --exact --nocapture` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

Occasionally, I will get

```
(exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)
```

instead of

```
(exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

so I suspect I am doing memory management wrong somehow. If anyone has any pointers (pun) on how to figure that part out, I would greatly appreciate it!

Background: I am writing a file manager app in the tauri framework (https://tauri.app/) to learn rust. I come from a python background.

The funny thing is that the code above works for the first copy action in the sense that I am actually able to paste the file in Explorer. If I try to copy another file afterwards my Tauri app crashes with no stack trace

2023-01-04 16:31 UTC, DoumanAsh requested changes
I left some comments which potentially might fix issue
I'll give it a better look tomorrow

2023-01-04 16:31 UTC, DoumanAsh commented on Cargo.toml
> +windows = { version = "0.43.0", features = ["Win32_UI_Shell", "Win32_Foundation"] }
this crate uses `winapi` so do not add `windows` as dep

2023-01-04 16:31 UTC, DoumanAsh commented on src/raw.rs
> +    let dropfiles = windows::Win32::UI::Shell::DROPFILES {
there is no point in creating this struct separately.
Just cast raw memory pointer to `*mut DROPFILES` and write into it using `ptr::write`

2023-01-04 16:31 UTC, DoumanAsh commented on src/raw.rs
> +    let path_size = files_bytes.len() * 2;
This is incorrect.
When you encode something into `utf-16` you already number of bytes as it is.
It is not characters so multiplication by 2 should be superfluous

2023-01-04 16:31 UTC, DoumanAsh commented on src/raw.rs
> +    let files_bytes: Vec<u16> = final_str.encode_utf16().collect();
use `MultiByteToWideChar` to convert to wide string format.

you can avoid creating intermediate buffer this way

To determine size of output you can use it with empty output buffer like here:
https://github.com/DoumanAsh/clipboard-win/blob/master/src/raw.rs#L336-L338

2023-01-04 16:31 UTC, DoumanAsh commented on src/raw.rs
> +    if unsafe { !SetClipboardData(formats::CF_HDROP, mem.get()).is_null() } {
Do `let _ = empty();` before calling any `SetClipboardData`

2023-01-04 16:31 UTC, DoumanAsh commented on src/raw.rs
> +            ptr::copy_nonoverlapping(
All C strings must have null terminating symbol, so I suspect you need to append `0` after writing file path.
Segmentation fault can be coming from that

So add something along lines of:
```rust
(ptr.as_ptr() as *mut u8).add(dropfiles_size + path_size).write(0)
```
I.e. you should have following memory layout:
```
<DROPFILES...>
<files_bytes...>
0
```

2023-01-04 16:33 UTC, DoumanAsh commented on src/raw.rs
> +    let path_size = files_bytes.len() * 2;
Side note, do not forget to add 1 byte for null terminating symbol

2023-01-05 03:34 UTC, DoumanAsh commented
@mchels I applied comments myself, please check

2023-01-05 04:16 UTC, DoumanAsh commented
Notices there is some issue, let me try to see if I can write test for this code

2023-01-05 04:24 UTC, DoumanAsh commented
@mchels I fixed memory corruption in my code, so now it should correctly set file from string.

Let me know how it looks to you.
I think for what you want it is better to have API that accepts list of strings, rather than single string

2023-01-05 19:48 UTC, mchels commented
>  I think for what you want it is better to have API that accepts list of strings, rather than single string

Absolutely agree. The code I pushed was just what I was able to do myself.
I will take a look at the rest tomorrow. Thank you for looking into this!

2023-01-08 16:05 UTC, mchels commented
@DoumanAsh I have pushed a commit that sets a list of strings rather than a single string. It seems to work for me.

2023-01-08 17:31 UTC, DoumanAsh approved these changes

2023-01-08 17:31 UTC, merged

2023-01-08 17:33 UTC, DoumanAsh commented
I released version 4.5.0